### ISSUE TITLE
Could not fetch repository

### ISSUE THREAD

**Issue by Sivarajani** [alexejsailer/git-analytics-docker#3]
Hi,
i tried to fetch the commits from my private repository after git clone. Getting could not fetch repository error message .

Please guide me to resolve this.

**Comment by arturChPl** [comment]
Have the same issue.
at com.dualexec.git.repository.fetcher.services.RepositoryFetcherBean.fetchAll(RepositoryFetcherBean.java:210) ~[classes!/:1.0.0-SNAPSHOT]

on URL command:
``curl -u admin:test -d "{\"command\": \"FETCH\"}" -H "Content-Type: application/json" -X POST `http://192.168.0.10:8090/repository-fetcher/api/v1/commands``

response is:
{"timestamp":1585071264119,"status":500,"error":"Internal Server Error","exception":"org.springframework.web.client.HttpServerErrorException","message":"500 ","path":"/repository-fetcher/api/v1/commands"}

**Comment by thomaspmorgan** [comment]
I have the same issue.

**Comment by alexejsailer** [comment]
Hi, sorry that I did not respond that long. But I will take a look to check whats wrong there.

**Comment by alexejsailer** [comment]
As I pushed new image versions in may, you should update your docker images. Could you please first delete all images from alexejsailer from your docker host and then run the compose file again. Also make sure, that your docker host has access to the repository folder, especially if you are using windows.
